### ISSUE TITLE
not able to build entity-fishing

### ISSUE THREAD

**Issue by angelosalatino** [kermitt2/entity-fishing#148]
Hi, I am following the guide here: https://nerd.readthedocs.io/en/latest/build.html

I am at the stage in which I am building entity fishing, and I get the following error: BUILD FAILED.

```
113 tests completed, 27 failed, 6 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.
```

The current version of Gradle I am using is 7.1.1.
JDK: java-11-openjdk.x86_64

Do you have any suggestion on how to get it running?

Thank you very much in advance.

Best regards

Here is a more comprehensive output from the terminal: https://pastebin.com/WhSSNeC6 (I used pastebin, because github won't allow me to paste such long text)

**Comment by kermitt2** [comment]
Hi @angelosalatino  !

From the test errors, it seems that Grobid is not installed and/or the grobid-home path is not indicated in the entity-fishing config file. 

[Grobid](https://github.com/kermitt2/grobid/) and [grobid-ner](https://github.com/kermitt2/grobid-ner/) are required to have entity-fishing building and running. 

(note: I am working on a Docker image for entity-fishing, because build and run is not straightfoward as you can see ;) )

**Comment by angelosalatino** [comment]
Hi @kermitt2,

I managed to get it going. Yes the grobid-home path was wrong. Then, I am not sure if this influences, I added all the languages of the model. Before I was trying only with the english language.

Thank you
