### ISSUE TITLE
General Statistics of Retrievable Wiki Entities 

### ISSUE THREAD

**Issue by ndenStanford** [kermitt2/entity-fishing#157]
Would you mind letting me know where I can see the general statistics of the retrievable wiki entities? I would love to understand the size of the retrievable knowledge base broken down into each entity category. If such statistics are not available, can you please elaborate on how can I read from the database directly? I am seeing that key and value of the database are encoded and I am not able to decode them since I do not know how it was encoded. 

Appreciate your attention to this matter :)

**Comment by ndenStanford** [comment]
Much appreciated the reply. I have a couple of follow-up questions. Does that mean all the fetched Wikipedia (total of around 62M from summing up all pages) and 18271696 Wikidata entities can be linked to the mentions in text? The rest of WIkidata id cannot.

**Comment by kermitt2** [comment]
@ndenStanford The current state of the tool is as follow:

- for a given language, only a Wikidata entity having a corresponding "page" in the language Wikipedia can be "linked" in context, because it requires some textual usage context (anchors), synonyms (redirections) and links for the disambiguation
- so the proportion of Wikidata entity that can be disambiguated in context depends on the language and its Wikipedia

It's why it's hard to support currently languages with less than one million Wikipedia pages. Without enough training material in the language, page and page interlinking, we don't have enough data to disambiguate terms. 

But I think it's still useful to have access to the whole Wikidata (the 100M entities) via the KB API because for example I have other tools doing more specialized entity mention extraction and I exploit and link these other entities directly. So the 100M entities are loaded. 

> It's also quite a surprise to see how small the number of loaded statements is compared to the number of concepts so I wonder why that is.

As I wrote, by default, we only load statements of an entity if this entity "exists" in at least one language-specific Wikipedia. It appears that usually the same subset of entities are present in the different Wikipedia, and not every pages in a Wikipedia correspond to a Wikidata entity (many Wikipedia pages are redirection, disambiguation page, category, etc. only articles are mapped to a Wikidata entity, for example around 6M for English, out of 18M pages).

It's possible to load all the statements by changing the config, for example I have an older version of entity-fishing with all statements loaded and it's more than 1B statements. Due to the size of the resulting DB and the extra time indexing this, it's turn off by the default.

**Comment by ndenStanford** [comment]
Thank you very much for the clarification :)
