### ISSUE TITLE
Output of scores

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/entity-fishing#77]
as agreed, we should rename `nerd_score` with `confidence_score` and remove `nerd_selector_score`. 

The confidence score (single output measurement for users) is taken from the output fo the selection regression model.

**Comment by tantikristanti** [comment]
Regarding this issue, selection scores are used as confidence scores in Json output result. The fix is done in a branch 'outputScores'


<img width="309" alt="screen shot 2018-10-15 at 11 46 48" src="https://user-images.githubusercontent.com/28044697/46943614-4954aa00-d070-11e8-85d9-552e405eccde.png">
