### ISSUE TITLE
Dockerfile for entity-fishing

### ISSUE THREAD

**Issue by rautant** [kermitt2/entity-fishing#94]
Hi! Are there any plans to create a Dockerfile (/docker-compose.yml) for this project (or some instructions on how to do that)?
I was hoping to get one for entity-fishing.

I know there was an issue about Docker image (https://github.com/kermitt2/entity-fishing/issues/21), but there was a problem including the knowledge base data into the image, but I imagine there should be a way of using volumes to store that data? (I'm not a Docker expert, but I've read that volumes could be used to handle large files.)

**Comment by lfoppiano** [comment]
Hi @rautant, indeed there is indeed an issue with the amount of data to be downloaded. This shoudl be first solved in the gradle build (adding a task automatically downloading the data, perhaps), and then the docker build could be simplified. 

Since there is already #21 on the same subject, I would close this ticket (will be referenced from there anyway).
